version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha  # gcloud is baked into this image
        auth:
          username: tdrhq
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew :assembleDebug
            ./gradlew :assembleDebugAndroidTest
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Test with Firebase Test Lab
          command: >
            cd ~/project && sudo gcloud firebase test android run \
              --app ./build/outputs/apk/debug/project-debug.apk \
              --test ./build/outputs/apk/androidTest/debug/project-debug-androidTest.apk \
              --results-bucket cloud-test-${GOOGLE_PROJECT_ID} \
              --directories-to-pull /sdcard/screenshots/com.facebook.testing.screenshot.example.test \
              --device-ids Pixel2 \
              --os-version-ids 27
      - run:
          name: Install gsutil dependency and copy test results data
          command: |
            sudo pip install -U crcmod
            sudo gsutil -m cp -r -U `sudo gsutil ls gs://cloud-test-${GOOGLE_PROJECT_ID}/ | tail -1` ${CIRCLE_ARTIFACTS}/ | true
      - run:
          name: Record to screenshotbot
          command: |
            wget https://screenshotbot.io/recorder-master.jar
            java -jar recorder-master.jar --dir ${CIRCLE_ARTIFACTS}/*/*/artifacts/screenshot_bundle.zip \
              --channel screenshotbot-example-circleci-test \
              --metadata ${CIRCLE_ARTIFACTS}/*/*/artifacts/metadata.xml \
              --is-production \
              --branch ${CIRCLE_BRANCH} \
              --api-key ${SCREENSHOTBOT_API_KEY} \
              --repo ${CIRCLE_REPOSITORY_URL} \
              --api-secret ${SCREENSHOTBOT_API_SECRET}
